"""Model.from_mesh: OBJ (+MTL), STL (ascii and binary), GLB with materials and node
transforms. Every mesh here is generated by the test (no third-party files)."""
import json
import struct

import numpy as np

from conftest import Model, solve
from oracles import check_model


def _box(x0, y0, z0, x1, y1, z1):
    v = np.array([[x, y, z] for x in (x0, x1) for y in (y0, y1) for z in (z0, z1)], dtype=float)
    faces = [(0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)]
    tris = [(a, b, c) for a, b, c, d in faces] + [(a, c, d) for a, b, c, d in faces]
    return v, np.array(tris)


def _sphere(r=50.0, n=24):
    th = np.linspace(0, np.pi, n + 1)
    ph = np.linspace(0, 2 * np.pi, 2 * n, endpoint=False)
    tris = []
    for i in range(n):
        for j in range(2 * n):
            p = lambda a, b: (r * np.sin(th[a]) * np.cos(ph[b % (2 * n)]), r * np.cos(th[a]),   # noqa: E731
                              r * np.sin(th[a]) * np.sin(ph[b % (2 * n)]))
            a, b, c, d = p(i, j), p(i + 1, j), p(i + 1, j + 1), p(i, j + 1)
            tris += [(a, b, c), (a, c, d)]
    return np.array(tris)


def test_obj_with_mtl_colour(tmp_path):
    v, t = _box(0, 0, 0, 80, 80, 80)
    (tmp_path / "c.mtl").write_text("newmtl Paint\nKd 0.7 0.0 0.0\n")
    lines = ["mtllib c.mtl", "usemtl Paint"] + [f"v {a} {b} {c}" for a, b, c in v]
    lines += [f"f {a + 1} {b + 1} {c + 1}" for a, b, c in t]
    (tmp_path / "cube.obj").write_text("\n".join(lines))
    m = Model.from_mesh(str(tmp_path / "cube.obj"), height_cm=8)
    assert m.V.shape == (10, 10, 25) and (m.V > 0).all()
    assert m.palette == ["red"]


def test_binary_stl_sphere_is_solid_and_round(tmp_path):
    tris = _sphere(50.0)
    data = b"\0" * 80 + struct.pack("<I", len(tris))
    for tri in tris:
        data += struct.pack("<3f", 0, 0, 0) + struct.pack("<9f", *tri.ravel()) + b"\0\0"
    (tmp_path / "ball.stl").write_bytes(data)
    m = Model.from_mesh(str(tmp_path / "ball.stl"), height_cm=10, colors=["yellow"], default_color="yellow")
    vol_mm3 = m.voxel_count() * 8 * 8 * 3.2
    assert abs(vol_mm3 / (4 / 3 * np.pi * 50 ** 3) - 1) < 0.15
    assert m.V[m.NX // 2, m.NZ // 2, m.NY // 2] > 0                      # filled, not a shell


def test_ascii_stl_and_z_up(tmp_path):
    v, t = _box(0, 0, 0, 16, 16, 64)                                      # tall along z
    out = ["solid t"]
    for a, b, c in t:
        out += ["facet normal 0 0 0", "outer loop"] + [f"vertex {x} {y} {z}" for x, y, z in v[[a, b, c]]]
        out += ["endloop", "endfacet"]
    (tmp_path / "post.stl").write_text("\n".join(out + ["endsolid t"]))
    m = Model.from_mesh(str(tmp_path / "post.stl"), height_cm=6.4, up="z")
    assert m.V.shape == (2, 2, 20)


def _glb(parts):
    """parts: [(verts, tris, rgba, node_extra)] -> GLB bytes, one node per part."""
    doc = {"asset": {"version": "2.0"}, "scene": 0, "scenes": [{"nodes": []}], "nodes": [], "meshes": [],
           "materials": [], "accessors": [], "bufferViews": [], "buffers": [{}]}
    blob = b""
    for k, (v, t, rgba, extra) in enumerate(parts):
        vb = v.astype("<f4").tobytes()
        ib = t.astype("<u2").ravel().tobytes()
        for data, target in ((vb, 34962), (ib, 34963)):
            doc["bufferViews"].append({"buffer": 0, "byteOffset": len(blob), "byteLength": len(data), "target": target})
            blob += data + b"\0" * (-len(data) % 4)
        doc["accessors"] += [{"bufferView": 2 * k, "componentType": 5126, "count": len(v), "type": "VEC3",
                              "min": v.min(0).tolist(), "max": v.max(0).tolist()},
                             {"bufferView": 2 * k + 1, "componentType": 5123, "count": t.size, "type": "SCALAR"}]
        doc["materials"].append({"pbrMetallicRoughness": {"baseColorFactor": rgba}})
        doc["meshes"].append({"primitives": [{"attributes": {"POSITION": 2 * k}, "indices": 2 * k + 1, "material": k}]})
        doc["nodes"].append(dict({"mesh": k}, **extra))
        doc["scenes"][0]["nodes"].append(k)
    doc["buffers"][0]["byteLength"] = len(blob)
    js = json.dumps(doc).encode()
    js += b" " * (-len(js) % 4)
    body = struct.pack("<II", len(js), 0x4E4F534A) + js + struct.pack("<II", len(blob), 0x004E4942) + blob
    return struct.pack("<4sII", b"glTF", 2, 12 + len(body)) + body


def test_glb_materials_and_node_transforms_build(tmp_path):
    body_v, body_t = _box(-40, 0, -24, 40, 96, 24)                       # 10 x 6 studs, 30 plates
    hat_v, hat_t = _box(-16, 0, -16, 16, 16, 16)
    # the hat sits on top via a translation, and a scale/rotation that must be honoured
    q = [0, np.sin(np.pi / 4), 0, np.cos(np.pi / 4)]                     # 90 degrees about y
    glb = _glb([(body_v, body_t, [0.02, 0.1, 0.6, 1], {}),
                (hat_v, hat_t, [0.9, 0.7, 0.0, 1], {"translation": [0, 96, 0], "rotation": q,
                                                     "scale": [1.5, 1.0, 1.0]})])
    (tmp_path / "toy.glb").write_bytes(glb)
    m = Model.from_mesh(str(tmp_path / "toy.glb"), height_cm=11.2)
    assert m.V.shape == (10, 6, 35)
    assert set(m.palette) == {"blue", "yellow"}
    yellow = m.palette.index("yellow") + 1
    xs, zs, ys = np.nonzero(m.V == yellow)
    assert ys.min() >= 29                                                 # on top of the body
    assert (xs.max() - xs.min() + 1, zs.max() - zs.min() + 1) == (4, 6)   # 4 wide, 6 deep after the turn
    model, built = solve(m, seeds=1)
    assert model["stats"]["passed"], model["stats"]["failures"]
    check_model(model, m.V, built, m.palette)
